name: Convert Markdown to PDF and Publish as Individual Assets

on:
  push:
    paths:
      - '**/*.md'

jobs:
  convert-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for release creation and file uploads

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra

    - name: Convert Markdown files to PDF
      run: |
        mkdir -p output
        shopt -s globstar nullglob
        for file in **/*.md; do
          filename=$(basename "$file" .md)
          pandoc "$file" -o "output/${filename}.pdf"
        done

    - name: Create GitHub Release and Upload PDFs
      uses: softprops/action-gh-release@v2
      with:
        tag_name: pdf-release
        name: Markdown PDFs
        files: output/*.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
